---
# tasks file for ansible-role-yum_config_manager
# - name: Include only enable specific repos tasks
#   include_tasks: enable_only.yml
#   when: "'only' in repositories"

# - name: Include enable / disable repos tasks
#   include_tasks: enable_disable.yml
#   when: "'only' not in repositories"

- name: Backup repo config file
  copy:
    src: "{{ rhui_config_path }}/{{ rhui_config_name }}"
    dest: "{{ rhui_config_path }}/{{ rhui_config_name }}.backup"
    remote_src: yes
    backup: no

- name: Output repo_config_file
  script: scripts/redhat-rhui-aws.py "{{ rhui_config_path }}/{{ rhui_config_name }}"
  args:
    executable: python
  register: repos

- name: Print all repos
  debug:
    msg: "{{ item }}"
  with_items:
    - "{{ repos.stdout_lines }}"

- name: Print repositories
  debug:
    msg: "{{ repositories }}"

- name: Disable repositories
  script: scripts/redhat-rhui-aws.py "{{ rhui_config_path }}/{{ rhui_config_name }}" -disable {{ item }}
  args:
    executable: python
  with_items:
    - "{{ repositories.disabled|default([]) }}"

- name: Enable repositories
  script: scripts/redhat-rhui-aws.py "{{ rhui_config_path }}/{{ rhui_config_name }}" -enable {{ item }}
  args:
    executable: python
  with_items:
    - "{{ repositories.enabled|default([]) }}"