---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: instance
    image: ami-000db10762d0c4c05
    instance_type: t2.micro
    vpc_subnet_id: subnet-38a38302
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  connection_options:
    ansible_user: ec2-user
  playbooks:
    converge: ../resources/playbooks/converge.yml
    cleanup: ../resources/playbooks/cleanup.yml
  inventory:
    host_vars:
      instance:
        ec2_driver: true
        rhsm_repositories:
          enabled:
            - rhel-7-server-rpms
            - rhel-7-server-optional-rpms
            - rhel-7-server-extras-rpms
            - rhel-server-rhscl-7-rpms
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
